name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install || echo "No dependencies to install"

      - name: Run lint
        run: |
          npm run lint > lint-report.txt || echo "Linting failed or skipped"

      - name: Run tests
        run: |
          npm test > test-report.txt || echo "Tests failed or skipped"

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: lint-report.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-report.txt
