name: Documentation Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install || echo "No dependencies to install"

      - name: Build documentation
        run: |
          echo "Building documentation..."
          mkdir -p docs-build
          cp -r docs/* docs-build/
          echo "Documentation built ✅"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-build
          commit_message: "Automated documentation update [ci skip]"
